### ISSUE TITLE
[温泉]鹿教湯温泉のところの氷の灯籠(1月過ぎ？）

### ISSUE THREAD

**Issue by CactusJack677** [itog/uedablog#11]
氷の灯籠が温泉付近に登場するシーズンがあって、バリきれい。

**Comment by itog** [comment]
http://www.kakeyu.or.jp/event/fuyu_tourou.html

平成27年12月25日(金) ～ 平成28年1月31日(日)まで毎日開催
午後4時半～午後9時頃(ロウソクの灯が消える)まで

**Comment by itog** [comment]
Fix.

http://ueda.pigmal.com/%E3%82%A4%E3%83%99%E3%83%B3%E3%83%88/%E9%B9%BF%E6%95%99%E6%B9%AF%E6%B8%A9%E6%B3%89-%E6%B0%B7%E7%81%AF%E7%AF%AD/
