### ISSUE TITLE
[お土産]みすゞ飴本舗

### ISSUE THREAD

**Issue by tomovwgti** [itog/uedablog#7]
主にジャム
http://misuzuame.com/

**Comment by itog** [comment]
カッコが全角でリジェクトしたい

**Comment by tomovwgti** [comment]
ほらよ

**Comment by itog** [comment]
LGTM

**Comment by itog** [comment]
Fix.

http://ueda.pigmal.com/%E3%82%B0%E3%83%AB%E3%83%A1/%E3%81%BF%E3%81%99%E3%82%9E%E9%A3%B4%E6%9C%AC%E8%88%97-%E9%A3%AF%E5%B3%B6%E5%95%86%E5%BA%97-2/
